Messagebox
RadicalFx/Radical.Windows.Presentation pull request #62
Opened 2019-01-18 17:46 UTC by nazarenomanco

Added the possibility to show a MessageBox from ViewModel with message

2019-01-19 16:51 UTC, mauroservienti requested changes
There are a couple more things that need to be changed, reviewing them from the iPad is not easy tho.

2019-01-19 16:51 UTC, mauroservienti commented on src/net40/Radical.Windows.Presentation/Messaging/Handlers/ShowMessageBoxRequestHandler.cs
> +            if (broker == null) throw new ArgumentNullException(nameof(broker));
Replace with Ensure.That( ... )

2019-01-19 16:51 UTC, mauroservienti commented on src/net40/Radical.Windows.Presentation/Messaging/Handlers/ShowMessageBoxRequestHandler.cs
> +            MessageBoxImage icon = message.Icon == null ? MessageBoxImage.None : (MessageBoxImage) message.Icon;
Use var whenever possible

2019-01-19 16:51 UTC, mauroservienti commented on src/net40/Radical.Windows.Presentation/Messaging/Handlers/ShowMessageBoxRequestHandler.cs
> +            MessageBoxButton button = message.Button == null ? MessageBoxButton.OK : (MessageBoxButton) message.Button;
Use var whenever possible

2019-01-19 16:51 UTC, mauroservienti commented on src/net40/Radical.Windows.Presentation/Messaging/Handlers/ShowMessageBoxRequestHandler.cs
> +            MessageBoxResult defaultResult = message.DefaultResult == null ? MessageBoxResult.None : (MessageBoxResult) message.DefaultResult;
Use var whenever possible

2019-01-19 16:51 UTC, mauroservienti commented on src/net40/Radical.Windows.Presentation/Messaging/Handlers/ShowMessageBoxRequestHandler.cs
> +            MessageBoxOptions options = message.Options == null ? MessageBoxOptions.None : (MessageBoxOptions) message.Options;
Use var whenever possible

2019-01-19 16:51 UTC, mauroservienti commented on src/net40/Radical.Windows.Presentation/Messaging/Handlers/ShowMessageBoxRequestHandler.cs
> +            MessageBoxResult result = MessageBox.Show(message.MessageBoxText, message.Caption, button,
Use var whenever possible

2019-01-19 16:51 UTC, mauroservienti commented on src/net40/Radical.Windows.Presentation/Messaging/Handlers/ShowMessageBoxRequestHandler.cs
> +            broker.Broadcast(this,new ShowMessageBoxResult(result));
Using the broker to broadcast message box results is not efficient. Message box results are interesting only for the message box invoker. Use an approach similar to the one used in #53: 
https://github.com/RadicalFx/Radical.Windows.Presentation/pull/53/files#diff-468e003a7a4be992b3538023879f6af5R23

2019-01-19 16:51 UTC, mauroservienti commented on src/net40/Radical.Windows.Presentation/Messaging/ShowMessageBoxResult.cs
> +    public class ShowMessageBoxResult
This entire class can be deleted if the results invocation uses the delegate approach

2019-01-21 21:01 UTC, nazarenomanco commented
@mauroservienti done !

2019-01-29 05:59 UTC, mauroservienti requested changes

2019-01-29 05:59 UTC, mauroservienti commented on src/net40/Radical.Windows.Presentation/Messaging/ShowMessageBoxResult.cs
> +    public class ShowMessageBoxResult
delete this file.

2019-01-29 05:59 UTC, mauroservienti commented on src/net40/Radical.Windows.Presentation/Messaging/ShowMessageBoxRequest.cs
> +        public Action<MessageBoxResult> MessageBoxClosed { get; set; }
rename this to `OnMessageBoxClosed`

2019-01-29 05:59 UTC, mauroservienti commented on src/net40/Radical.Windows.Presentation/Messaging/Handlers/ShowMessageBoxRequestHandler.cs
> +            Ensure.That(broker).Named(() => broker).IsNotNull();
do not use the labda, it's too slow. Replace with `.Named("broker")` or better yet `.Named(nameof(broker))`.

2019-01-29 05:59 UTC, mauroservienti commented on src/net40/Radical.Windows.Presentation/Messaging/ShowMessageBoxRequest.cs
> +        ///
Missing documentation 😄 

> Message box closed callback, invoked when the message box is closed by the user.

2019-12-10 20:27 UTC, mauroservienti commented
This needs to be recreated in Radical.Windows as soon as https://github.com/RadicalFx/Radical.Windows/pull/111 is merged

2025-05-01 07:08 UTC, closed without merging